version: '3'
services:
  golang:
    image: golang:1.17
    restart: unless-stopped
    ports:
    - 8080:8080
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
    - .:/app
    - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run .

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
    - 5672:5672
    - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password